newsletter:
    resource: "@PixellHubNewsletterBundle/Controller/NewsletterEntityController.php"
    type:     annotation
    
public:
    resource: "@PixellHubNewsletterBundle/Controller/PublicController.php"
    type:     annotation