newsletter:
    resource: "@PixellNewsletterBundle/Controller/NewsletterEntityController.php"
    type:     annotation
    
public:
    resource: "@PixellNewsletterBundle/Controller/PublicController.php"
    type:     annotation